# Use the official Tomcat base image
FROM tomcat:latest

# Copy your web application to the Tomcat webapps directory
COPY ./pt-web-app.war /usr/local/tomcat/webapps/ROOT.war

# Expose the default Tomcat port
EXPOSE 8080
